//setTokenActions
export const SET_TOKEN = 'SET_TOKEN';

//userPlaylistsActions
export const FETCH_PLAYLISTS_START = 'FETCH_PLAYLISTS_START';
export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';
export const FETCH_PLAYLISTS_ERROR = 'FETCH_PLAYLISTS_ERROR';
export const FETCH_PLAYLIST_TRACKS_START = 'FETCH_PLAYLIST_TRACKS_START';
export const FETCH_PLAYLIST_TRACKS_SUCCESS = 'FETCH_PLAYLIST_TRACKS_SUCCESS';
export const FETCH_PLAYLIST_TRACKS_ERROR = 'FETCH_PLAYLIST_TRACKS_ERROR';

//changeHeaderActions
export const CHANGE_HEADER_TITLE = 'CHANGE_HEADER_TITLE';

//userActions
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
