//setTokenActions
export const SET_TOKEN = 'SET_TOKEN';

//userPlaylistsActions
export const FETCH_PLAYLISTS_START = 'FETCH_PLAYLISTS_START';
export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';
export const FETCH_PLAYLISTS_ERROR = 'FETCH_PLAYLISTS_ERROR';
